### PR TITLE
* FIX [codec] memory leaks.

### LINKED ISSUE #30: Memory leaks
**Describe the bug**
Memory leaks at conn_handler();

**Expected behavior**
Be fixed.

**Actual Behavior**
Describe what occurred.

**To Reproduce**

-  No property 
- No Client id

```bash
mqtt pub -t "topic" -m "hello" -q 0 -v -d 
```

then shutdown nanomq.

** Environment Details **
 - NNG version: latest
 - Operating system and version
 - Compiler and language used
 - Shared or static library

**Additional context**
```bash
Fri Mar 11 22:24:22 2022 tcptran_pipe_recv_cb: remain_len 0 cparam 0x61100000ff40 clientid nanomq-ce5e90ee username (null) proto 5

Fri Mar 11 22:24:22 2022 tcptran_pipe_recv_cb: The type of msg is e0
Fri Mar 11 22:24:22 2022 nni_aio_finish_sync: Hunky dory(0)
Fri Mar 11 22:24:22 2022 nano_pipe_recv_cb: ######### nano_pipe_recv_cb ############
Fri Mar 11 22:24:22 2022 nano_pipe_close:  ############## nano_pipe_close ############## 
Fri Mar 11 22:24:22 2022 nni_aio_finish_error: Object closed(7)
Fri Mar 11 22:24:22 2022 nni_aio_finish_sync: Hunky dory(0)
Fri Mar 11 22:24:22 2022 server_cb: RECV  ^^^^ ctx3 ^^^^

Fri Mar 11 22:24:22 2022 decode_pub_message: cmd: 3, retain: 0, qos: 0, dup: 0, remaining length: 112
Fri Mar 11 22:24:22 2022 decode_pub_message: topic: [$SYS/brokers/disconnected], qos: 0
Fri Mar 11 22:24:22 2022 decode_pub_message: used pos: [27]
Fri Mar 11 22:24:22 2022 decode_pub_message: payload: [{"username":"(null)","ts":1054720134,"reason_code":"0","client_id":"nanomq-ce5e90ee"}], len = 85
Fri Mar 11 22:24:22 2022 handle_pub: pipe_info size: [0]
Fri Mar 11 22:24:22 2022 server_cb: ERROR it should not happen
Fri Mar 11 22:24:22 2022 conn_param_free: destroy conn param
Fri Mar 11 22:24:22 2022 nni_aio_finish: Hunky dory(0)
Fri Mar 11 22:24:22 2022 nano_pipe_recv_cb: ERROR: pipe is closed abruptly!!
Fri Mar 11 22:24:22 2022 nano_pipe_stop:  ########## nano_pipe_stop ########## 
Fri Mar 11 22:24:22 2022 tcptran_pipe_recv_cb: end of tcptran_pipe_recv_cb: synch! 0x61300000ffc0

Fri Mar 11 22:24:22 2022 server_cb: WAIT ^^^^ ctx3 ^^^^
Fri Mar 11 22:24:22 2022 nano_pipe_fini:  ########## nano_pipe_fini ########## 
Fri Mar 11 22:24:22 2022 server_cb: total pipes: 0
Fri Mar 11 22:24:22 2022 free_pub_packet: free topic
Fri Mar 11 22:24:22 2022 free_pub_packet: free payload
Fri Mar 11 22:24:22 2022 free_pub_packet: free pub_packet
Fri Mar 11 22:24:22 2022 init_pipe_content: pub_handler: init pipe_info
Fri Mar 11 22:24:22 2022 nng_ctx_recv:  ######## nng_ctx_recv context id 3 ######## 
Fri Mar 11 22:24:22 2022 nano_ctx_recv: nano_ctx_recv start 0x6100000003b0
^C
Broker exit(0).

=================================================================
==2322825==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x7f61703a6dc6 in calloc (/lib/x86_64-linux-gnu/libasan.so.5+0x10ddc6)
    #1 0x559f675a9e33 in nni_zalloc ../nng/src/platform/posix/posix_alloc.c:26
    #2 0x559f6757a0f2 in nng_zalloc ../nng/src/nng.c:64
    #3 0x559f675efeb8 in property_alloc ../nng/src/supplemental/mqtt/mqtt_codec.c:1939
    #4 0x559f675f0466 in property_set_value_str ../nng/src/supplemental/mqtt/mqtt_codec.c:2056
    #5 0x559f675bbc11 in conn_handler ../nng/src/sp/protocol/mqtt/mqtt_parser.c:587
    #6 0x559f6763a192 in tcptran_pipe_nego_cb ../nng/src/sp/transport/mqtt/broker_tcp.c:337
    #7 0x559f675a4412 in nni_taskq_thread ../nng/src/core/taskq.c:50
    #8 0x559f675a59ea in nni_thr_wrap ../nng/src/core/thread.c:94
    #9 0x559f675ae1e4 in nni_plat_thr_main ../nng/src/platform/posix/posix_thread.c:266
    #10 0x7f617028058f in start_thread nptl/pthread_create.c:463

SUMMARY: AddressSanitizer: 64 byte(s) leaked in 1 allocation(s).
```

### PR DESCRIPTION
**Pull request by alvin1221**
fixes #30

### CODE REVIEW

File: src/sp/protocol/mqtt/mqtt_parser.c [hunk 1]
```diff
@@ -586,6 +586,9 @@ conn_handler(uint8_t *packet, conn_param *cparam)
 		property *assigned_cid =
 		    property_set_value_str(ASSIGNED_CLIENT_IDENTIFIER,
 		        cparam->clientid.body, cparam->clientid.len, false);
+		if (cparam->properties == NULL) {
+			cparam->properties = property_alloc();
```
Comment (lee-emqx) [inline src/sp/protocol/mqtt/mqtt_parser.c:590]: I feel confused why alloc can fix memory leak.

Comment (alvin1221) [reply src/sp/protocol/mqtt/mqtt_parser.c:590]: Becuase _property_set_value_str()_ will alloc new memory for  _assigned_cid_ . If _cparam->properties_ is _NULL_, then property_free() is unable  to free _assigned_cid_.

Comment (lee-emqx) [reply src/sp/protocol/mqtt/mqtt_parser.c:590]: If cparam->properties is NULL, should property_append return error ?

**Review by JaylinYu — APPROVED** [review]
