### PR TITLE
Fix #812

### LINKED ISSUE #812: Possible uninitialized variable causing seg fault with optimizations.
**Describe the bug**
 The variable described below warns as unitialized.  When I run the code, it does indeed fail at that line, only when built with optimizations on.  I can turn them off, but I figured I would report it here in case this is a legitimate behavior.  I am not well versed with C, so please excuse me if I am wrong about the source of my segmentation fault.
```
In function 'get_var_integer',
    inlined from 'ws_msg_adaptor' at ../nng/src/sp/protocol/mqtt/mqtt_parser.c:436:8:
../nng/src/sp/protocol/mqtt/mqtt_parser.c:170:18: warning: 'pos' is used uninitialized [-Wuninitialized]
  170 |         uint32_t p = *pos;
```

**Expected behavior**
No segmentation fault in `get_var_integer` function.

**Actual Behavior**
A segmentation fault when some subcriptions are sent to the broker.
GDB core dump: (w/o symbols)
```
#0  0x0000005592090178 in get_var_integer ()
No symbol table info available.
#1  0x00000055920905b0 in fixed_header_adaptor ()
No symbol table info available.
#2  0x000000559215050c in tcptran_pipe_recv_cb ()
No symbol table info available.
#3  0x0000005592086a30 in nni_taskq_thread ()
No symbol table info available.
#4  0x00000055920870f8 in nni_thr_wrap ()
No symbol table info available.
#5  0x00000055920893d0 in nni_plat_thr_main ()
No symbol table info available.
#6  0x0000007fbd970ce4 in ?? ()
No symbol table info available.
#7  0x0000007fb905f1a0 in ?? ()
No symbol table info available.
```
```
(gdb) info symbol 0x0000005592090178
get_var_integer + 16 in section .text of /XXXX
```

Nanomq log:
```
2024-01-13 20:04:50 [3354] TRACE ../nng/src/core/taskq.c:289 nni_taskq_sys_init: result is 8
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1144 print_conf: This NanoMQ instance configured as:
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1147 print_conf: tcp url:                  nmq-tcp://0.0.0.0:1883 
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1150 print_conf: websocket url:            nmq-ws://0.0.0.0:8083/mqtt
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1168 print_conf: daemon:                   false
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1170 print_conf: num_taskq_thread:         8
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1172 print_conf: max_taskq_thread:         8
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1174 print_conf: parallel:                 8
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1175 print_conf: property_size:            32
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1176 print_conf: max_packet_size:          10240
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1177 print_conf: client_max_packet_size:   10240
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1179 print_conf: max_mqueue_len:           2048
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1180 print_conf: max_inflight_window:      2048
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1181 print_conf: max_awaiting_rel:         10s
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1182 print_conf: await_rel_timeout:        10s
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1183 print_conf: retry_interval:           10s
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1184 print_conf: keepalive_multiplier:     1250.000000
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1188 print_conf: http server port:         8081
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1189 print_conf: http server limit_conn:   2
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1190 print_conf: http server username:     admin
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1192 print_conf: http server auth type:    basic
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1200 print_conf:        public key file:      /etc/certs/jwt/jwtRS256.key.pub
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1220 print_conf: allow_anonymous:          true
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1224 print_conf: acl_nomatch:              allow
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1226 print_conf: enable_acl_cache:         on
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1228 print_conf: acl_cache_max_size:       32
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1230 print_conf: acl_cache_ttl:            60
2024-01-13 20:04:50 [3354] INFO  ../nng/src/supplemental/nanolib/conf.c:1231 print_conf: acl_deny_action:          ignore
2024-01-13 20:04:50 [3354] INFO  ../nanomq/apps/broker.c:1340 store_pid: 3354
2024-01-13 20:04:50 [3354] DEBUG ../nng/src/supplemental/nanolib/mqtt_db.c:385 dbtree_node_new: New node: []
2024-01-13 20:04:50 [3354] DEBUG ../nng/src/supplemental/nanolib/mqtt_db.c:385 dbtree_node_new: New node: []
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:912 broker: db init finished
2024-01-13 20:04:50 [3354] DEBUG ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1360 nng_nmq_tcp0_open: open up nmq tcp0 protocol.
2024-01-13 20:04:50 [3354] DEBUG ../nng/src/sp/protocol.c:40 nni_proto_mqtt_open:  nng internal init finished! Listener start
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d44328 &&&&&&&&&
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:527 nano_sock_init: ************* nano_sock_init 0x5576d44218 *************
2024-01-13 20:04:50 [3354] DEBUG ../nng/src/sp/protocol.c:42 nni_proto_mqtt_open: mqtt socket opened!
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:921 broker: listener init finished
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:927 broker: HTTP service initialization
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:937 broker: HTTP init finished
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:943 broker: webhook init finished
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d45e70 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d46250 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d465c0 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d46930 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d46ca0 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d47010 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d47490 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d47800 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:1027 broker: NanoMQ context initialization
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d47b70 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d47ff0 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d48680 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:325 nano_ctx_init: &&&&&&&& nano_ctx_init 0x5576d48b00 &&&&&&&&&
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [1] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 1 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d45e70
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [2] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 2 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d46250
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [3] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 3 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d465c0
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [4] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 4 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d46930
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [5] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 5 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d46ca0
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [6] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 6 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d47010
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [7] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 7 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d47490
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:270 server_cb: INIT ^^^^^^^^ ctx [8] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 8 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d47800
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:273 server_cb: INIT ^^^^^^^^ extra ctx [10] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 10 ######## 
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:273 server_cb: INIT ^^^^^^^^ extra ctx [12] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 12 ######## 
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:273 server_cb: INIT ^^^^^^^^ extra ctx [14] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 14 ######## 
2024-01-13 20:04:50 [3354] DEBUG ../nanomq/apps/broker.c:273 server_cb: INIT ^^^^^^^^ extra ctx [16] ^^^^^^^^ 

2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 16 ######## 
2024-01-13 20:04:50 [3354] INFO  ../nanomq/web_server.c:512 start_rest_server: http://0.0.0.0:8081/api/v4
2024-01-13 20:04:50 [3374] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 17 ######## 
2024-01-13 20:04:50 [3354] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 19 ######## 
2024-01-13 20:04:50 [3374] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 18 ######## 
NanoMQ Broker is started successfully!
2024-01-13 20:04:55 [3360] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:1583 tcptran_pipe_start: tcptran_pipe_start!
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:297 tcptran_pipe_nego_cb: start tcptran_pipe_nego_cb max len 12 pipe_addr 0x7f50000b70 gotrx 0 wantrx 12

2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:297 tcptran_pipe_nego_cb: start tcptran_pipe_nego_cb max len 12 pipe_addr 0x7f50000b70 gotrx 5 wantrx 57

2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:567 conn_handler: remaining length: 55
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:578 conn_handler: pro_name: MQTT
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:581 conn_handler: pro_ver: 4
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:589 conn_handler: conn flag:4
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:622 conn_handler: pos after property: [12]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:642 conn_handler: clientid: [calypso] [7]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:643 conn_handler: pos after clientid: [21]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:678 conn_handler: will_topic: Calypso/Status 0
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:679 conn_handler: pos after will topic body: [37]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:694 conn_handler: will_msg: Calypso is offline 0
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:695 conn_handler: pos after will msg: [57]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:725 conn_handler: pos: [57] len: [55]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:177 tcptran_pipe_init:  ************ tcptran_pipe_init [0x7f50000b70] ************ 
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:606 nano_pipe_init: ##########nano_pipe_init###############
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:643 nano_pipe_start:  ########## nano_pipe_start ########## 
2024-01-13 20:04:55 [3361] DEBUG ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:674 nano_pipe_start: client connected! addr [127.0.0.1 port [27837]

2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/mqtt_parser.c:1239 verify_connect: no valid entry in auth list
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1035 nano_pipe_recv_cb:  ######### nano_pipe_recv_cb ######### 
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:1545 tcptran_pipe_recv_start: *** tcptran_pipe_recv_start ***

2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1170 nano_pipe_recv_cb: currently processing pipe_id: 1257963498
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/apps/broker.c:278 server_cb: RECV  ^^^^ ctx1 ^^^^

2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:379 nano_ctx_send:  #### nano_ctx_send with ctx 0x5576d45e70 msg type 20 #### 
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:394 nano_ctx_send:  ******** working with pipe id : 1257963498 ctx ******** 
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:1465 tcptran_pipe_send:  ########### tcptran_pipe_send ########### 
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:1425 tcptran_pipe_send_start: ########### tcptran_pipe_send_start ###########
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1499 decode_pub_message: cmd: 3, retain: 0, qos: 0, dup: 0, remaining length: 190
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1547 decode_pub_message: topic: [$SYS/brokers/connected], len: [22], qos: 0
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1592 decode_pub_message: used pos: [24]
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1603 decode_pub_message: payload: [{"username":"(null)", "ts":1705176295451,"proto_name":"MQTT","keepalive":20,"return_code":"0","proto_ver":4,"client_id":"calypso","clean_start":0, "IPv4":"127.0.0.1"}], len = 166
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1186 handle_pub: pipe_info size: [0]
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:1176 nano_pipe_recv_cb: end of nano_pipe_recv_cb 0x5576d45e70
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/apps/broker.c:526 server_cb: WAIT ^^^^ ctx1 ^^^^
2024-01-13 20:04:55 [3361] TRACE ../nanomq/apps/broker.c:536 server_cb: total pipes: 0
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1282 free_pub_packet: free topic
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1298 free_pub_packet: free payload
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:1304 free_pub_packet: free pub_packet
2024-01-13 20:04:55 [3361] DEBUG ../nanomq/pub_handler.c:84 init_pipe_content: pub_handler: init pipe_info
2024-01-13 20:04:55 [3366] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:516 nmq_tcptran_pipe_send_cb:  ################ nmq_tcptran_pipe_send_cb [0x7f50000b70] ################ 
2024-01-13 20:04:55 [3365] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:606 tcptran_pipe_recv_cb: tcptran_pipe_recv_cb 0x7f50000b70

2024-01-13 20:04:55 [3361] TRACE ../nng/src/nng.c:390 nng_ctx_recv:  ######## nng_ctx_recv context id 1 ######## 
2024-01-13 20:04:55 [3366] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:530 nmq_tcptran_pipe_send_cb: tcp socket sent 4 bytes iov 0
2024-01-13 20:04:55 [3361] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:959 nano_ctx_recv: nano_ctx_recv start 0x5576d45e70
2024-01-13 20:04:55 [3366] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:1425 tcptran_pipe_send_start: ########### tcptran_pipe_send_start ###########
2024-01-13 20:04:55 [3366] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:1435 tcptran_pipe_send_start: aio not functioning
2024-01-13 20:04:55 [3366] TRACE ../nng/src/sp/protocol/mqtt/nmq_mqtt.c:902 nano_pipe_send_cb: ******** nano_pipe_send_cb 1257963498 ****
2024-01-13 20:04:55 [3365] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:631 tcptran_pipe_recv_cb: newly recevied 2 totoal received: 2  pos: 2 len : 0
2024-01-13 20:04:55 [3365] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:633 tcptran_pipe_recv_cb: still need byte count:0 > 0

2024-01-13 20:04:55 [3365] TRACE ../nng/src/sp/transport/mqtt/broker_tcp.c:678 tcptran_pipe_recv_cb: pipe 0x7f50000b70 header got: e0 0 0 4 4d, 2!!

Segmentation fault
```

**To Reproduce**
Unfortunately I do not know exactly what type of subscription sent to nanomq could cause this, only the source of the actual segmentation fault.

** Environment Details **
 - NanoMQ version -> 0.20.8
 - Operating system and version -> Buildroot custom OS **(built all packages from source)**
 - Compiler and language used -> gcc v13 with **aarch64** toolchain. (`-Os`)
 - testing scenario -> `get_var_integer` does not have a warning for unitialized variable, so the segmentation fault cannot happen.

**Client SDK**
Connected via `paho-mqtt` rust bindings, segmentation faults on the initial subscription.

**Additional context**
I cannot reproduce reliably on x86_64, perhaps I am building it wrong on the host.  I can just  reproduce on aarch64.
Please let me know if there is any other debugging info I can provide.

### PR DESCRIPTION
**Pull request by JaylinYu**

### CODE REVIEW

**Comment by JaylinYu** [comment]
thanks， will fix ci and have a release this month!

**Review by lee-emqx — APPROVED** [review]

File: src/sp/transport/mqtt/broker_tcp.c [hunk 1]
```diff
@@ -739,27 +743,20 @@ tcptran_pipe_recv_cb(void *arg)
...
 		rv = MALFORMED_PACKET;
 		goto recv_error;
 	}
-
-	fixed_header_adaptor(p->rxlen, msg);
-	nni_msg_set_conn_param(msg, cparam);
-	// duplicated with fixed_header_adaptor
-	nni_msg_set_remaining_len(msg, len);
+	// fixed_header_adaptor(p->rxlen, msg);
+	nni_msg_set_remaining_len(msg, nni_msg_len(msg));
```
Comment (wanghaEMQ) [inline src/sp/transport/mqtt/broker_tcp.c:757]: Already set at 722line

**Review by wanghaEMQ — COMMENTED** [review]
And should we also change the nego cb part?

File: src/sp/transport/mqtt/broker_tcp.c (hunk 1 above)
Comment (JaylinYu) [reply src/sp/transport/mqtt/broker_tcp.c:757]: oh sure
